/**
 * Cuttlefish identity allocator — TS port of the shipped Python allocator
 * (cuttlefish-theme/color/identity.py, PR#1 head 7409e67).
 *
 * The port must reproduce the Python allocator's CONTRACT, pinned by
 * Python-generated fixture vectors (the "200 shared vectors"): the same
 * session ids and live sets produce the same identity colours, farthest-point
 * selection, reserved-arc exclusion, and crowded detection.
 *
 * Fixtures: src/field/fixtures/identity-vectors.json, generated by
 * scripts/generate-identity-vectors.py against the plugin repo at the pinned
 * commit — regeneration instructions in the script header.
 */
import { describe, expect, it } from 'vitest'

import { allocate, allocateMany, MIN_IDENTITY_DISTANCE } from './identity'

const vectors: Array<{
  id: string
  live: string[]
  hex: string
  separation: number | null
  crowded: boolean | null
}> = (await import('./fixtures/identity-vectors.json')).default

describe('cuttlefish identity allocator (pinned to Python vectors)', () => {
  it('reproduces every pinned vector exactly', () => {
    expect(vectors.length).toBeGreaterThanOrEqual(200)
    for (const v of vectors) {
      const got = allocate(v.id, v.live)
      expect(got.hex, `hex for ${v.id} with ${v.live.length} live peers`).toBe(v.hex)
      if (v.separation !== null) {
        expect(got.separation).toBeCloseTo(v.separation, 5)
      }
      if (v.crowded !== null) {
        expect(got.crowded).toBe(v.crowded)
      }
    }
  })

  it('never allocates inside the reserved alarm arcs', () => {
    const many = Array.from({ length: 60 }, (_, i) => allocate(`reserved-probe-${i}`, []))
    for (const c of many) {
      const h = c.oklch.h
      const reserved = (h >= 5 && h <= 48) || (h >= 62 && h <= 102)
      expect(reserved, `hue ${h} for a session must not be reserved`).toBe(false)
    }
  })

  it('holds the separation floor at 8 concurrent sessions', () => {
    const ids = ['tori-main', 'zivyra', 'tilola', 'chef', 'wise', 'rinera', 'mac01', 'vps-01']
    const out = allocateMany(ids)
    expect(out.length).toBe(ids.length)
    let worst = Infinity
    for (let i = 0; i < out.length; i++) {
      for (let j = i + 1; j < out.length; j++) {
        worst = Math.min(worst, out[i]!.distanceTo(out[j]!))
      }
    }
    expect(worst).toBeGreaterThanOrEqual(MIN_IDENTITY_DISTANCE)
  })

  it('is deterministic for a given (session, live) pair', () => {
    const live = ['#718FFF', '#FF94E7', '#3DDC97']
    const a = allocate('determinism-probe', live)
    const b = allocate('determinism-probe', live)
    expect(a.hex).toBe(b.hex)
    expect(a.hex).not.toBe(allocate('determinism-probe-2', live).hex)
  })
})
